# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VKApp_KonishchevIvan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKApp_KonishchevIvan
	pod 'RealmSwift'
	pod "PromiseKit"
end
